### ISSUE TITLE
Using `moonpool` to write parallel code that works well for both Ocaml 4.xx and 5.xx?

### ISSUE THREAD

**Issue by zoj613** [c-cube/moonpool#31]
Suppose I have the following code:
```ocaml
List.iter
  (fun x -> print_endline @@ string_of_int x) @@ List.init 10 Fun.id
```
and 
```ocaml
List.concat_map (fun x -> [x * x]) @@ List.init 10 Fun.id
```
Is there a way I can use moonpool to parallelize the above snippets such that the code works seamlessly in both Ocaml 4.xx and 5.xx, and if the i'm using 5.xx the moonpool automatically takes advantage of multicore features?

**Comment by c-cube** [comment]
On Sat, 14 Sep 2024, zoj613 wrote:
> Suppose I have the following code:
> ```ocaml
> List.iter
>   (fun x -> print_endline @@ string_of_int x) @@ List.init 10 Fun.id
> ```

For this you could make a runner (e.g. `Ws_pool.create()`) and then make
a task per iteration:


```ocaml
List.iter (fun x ->
  Moonpol.run_async runner (fun () -> print_endline …))
  (List.init 10 Fun.id)
```

> and 
> ```ocaml
> List.concat_map (fun x -> [x * x]) @@ List.init 10 Fun.id
> ```
> Is there a way I can use moonpool to parallelize the above snippets such that the code works seamlessly in both Ocaml 4.xx and 5.xx, and if the i'm using 5.xx the moonpool automatically takes advantage of multicore features?

For this you could use futures (without `await` which only works on
5.xx):

```ocaml
#List.map (fun x -> Moonpool.spawn ~on:runner (fun () -> [x;x])) [1;2;3]
  |> Moonpool.Fut.join_list
  |> Moonpool.Fut.wait_block_exn;;
- : int list list = [[1; 1]; [2; 2]; [3; 3]]
```
