### ISSUE TITLE
Persisting domains after `Pool.shutdown pool`

### ISSUE THREAD

**Issue by igarnier** [c-cube/moonpool#7]
# Descrition of the issue

I'm toying with `moonpool` to parallelize some sampling library. In one of my tests, after I finish performing the compute-intensive work I perform a call to `Unix.fork` which fails with the following error:

```
raised exception `Failure("Unix.fork may not be called while other domains were created")`
on `()`
Raised by primitive operation at Unix in file "unix.ml" (inlined), line 213, characters 0-46
Called from Plot.GP_run.run_script.(fun) in file "gnuplot/src/plot.ml", line 1100, characters 10-22
Called from Dagger_tests__Poly.run in file "dagger/test/poly.ml", line 167, characters 2-29
Called from Dagger_tests__Poly.tests.(fun) in file "dagger/test/poly.ml", line 172, characters 6-12
Called from QCheck2.Test.run_law.loop in file "src/core/QCheck2.ml", line 1644, characters 27-32
Called from QCheck2.Test.run_law in file "src/core/QCheck2.ml", line 1649, characters 6-18
Called from QCheck2.Test.check_state_input in file "src/core/QCheck2.ml", line 1772, characters 2
```

My interpretation is that despite having performed a call to `Pool.shutdown`, the domains created by `moonpool` persist. I grepped the moonpool sources and I didn't see a `Domain.join`. I may totally be wrong though: the error message could be understood as "creating domains prevents forever to fork your process, even after the extra domains complete".

# Steps to reproduce

- clone the branch `dagger-moonpool-issue` on `https://gitlab.com/igarnier/monorepo`
- `cd dagger`
- `dune build @runtest`

The failing test is `dagger/test/poly.ml`, the call to `Unix.fork` is hidden in `gnuplot/src/plot.ml`

**Comment by igarnier** [comment]
Thinking a bit more, I realize that it's not up to pools to manage domain resources, since several pools might run on the same set of domains. I still don't know how to proceed!

**Comment by c-cube** [comment]
It's a relevant issue I think. There have been discussions elsewhere about this kind of pool being more flexible. I think domains could be initialized lazily/on demand, and have a sort of refcounting to know when to stop (when all threads running on it are done).
